### ISSUE TITLE
Missing Data : Image 909 to 999

### ISSUE THREAD

**Issue by Ashishrout1999** [ArunBaskaran/Image-Driven-Machine-Learning-Approach-for-Microstructure-Classification-and-Segmentation-Ti-6Al-4V#2]
Hi, hope you are doing well. I just went through your excellent paper on classification and segmentation of Ti-64 microstructures.

However while going through dataset, I found that images from 909 to 999 is missing. Instead there has been some repetition of images in both 'Image 1' and 'Image 2' folder.

Hence could you please provide a fix ?

**Comment by ArunBaskaran** [comment]
Hey Ashish,
Hope you are doing well too. Thank you for bringing this issue to my attention. The images were missing because the folder initially had 1100 images due to an oversight. Github only allows 1000 files per directory, and I am guessing that images 901-1000 were the last 100 files on the upload queue. 

I have fixed the issue now. Images1 has image_1.png to image_1000.png, and Images 2 has the image_1001.png to image_1225.png.

**Comment by Ashishrout1999** [comment]
Thanks for the quick fix.
